feat(lab): use prettier, add pr lint ci, add lint rules
DHI/react-components pull request #111
Opened 2021-04-23 11:45 UTC by rihr

Resolves #106

Prettier, prettierrc and .editorconfig is now used for formatting - eslint will still show formatting errors in the editor.
Added more eslint rule extensions:
- @typescript-eslint/recommended
- @typescript-eslint/recommended-requiring-type-checking
- eslint-comments/recommended

Added linting CI in PRs

Fixed most lint errors and warnings according to new rules

2021-04-23 11:56 UTC, bertearazvan commented
Does it make sense for this PR to trigger a release of the package?

2021-04-23 11:58 UTC, rihr commented
> 
> 
> Does it make sense for this PR to trigger a release of the package?

Not really but the code does get changed

2021-04-23 12:01 UTC, bertearazvan approved these changes
Looks good 👍🏼

2021-04-23 12:02 UTC, bertearazvan commented
> > Does it make sense for this PR to trigger a release of the package?
> 
> Not really but the code does get changed

Then maybe I would make it a `fix` instead

2021-04-23 12:27 UTC, rihr commented on packages/react-components-lab/src/components/Snackbar/SnackbarProvider.tsx
> +  message?: any;
I considered changing it but I don't know what the functionality of the snackbar is - up to @rosudhi

2021-04-23 15:15 UTC, rosudhi requested changes
All seems good.

2021-04-23 15:24 UTC, rosudhi approved these changes

2021-04-23 15:49 UTC, rosudhi requested changes
The idea is message will support not only string but html tag as well, hence please change into `String | ReactNode`  instead.

2021-04-26 09:08 UTC, rosudhi commented on packages/react-components-lab/src/components/Snackbar/SnackbarProvider.tsx
>    const showMessage = (message: string, options: SnackbarProps) => {
this also need to be changed as well

2021-04-26 09:09 UTC, rosudhi commented on packages/react-components-lab/src/components/Snackbar/types.ts
> +  showMessage(message: string, options?: SnackbarProps): void;
this also need to be changed as well

2021-04-26 09:12 UTC, rosudhi requested changes
Forgot to add comments in specific line that need to be changed

2021-04-26 09:34 UTC, bertearazvan reviewed
I can still see many `any` for `msg` or so. Shouldn't those be also `string | ReactNode`?

2021-04-26 09:34 UTC, bertearazvan commented on .github/workflows/pr-lab.yml
> +name: CI - PR Lint
```suggestion
name: CI - Lab PR Lint
```

2021-04-26 09:34 UTC, bertearazvan commented on .github/workflows/pr-lab.yml
> +    branches:
I am not sure if this is correct, but I will count on your testing. Not sure if `push` should be removed.

2021-04-26 11:57 UTC, rosudhi commented
so far i can see, there are two line more, they are in SnackProvider.tsx file.
1.  Change into `String | ReactNode`
![image](https://user-images.githubusercontent.com/46663012/116078544-f2a89c00-a6c0-11eb-8d3f-177b928dd011.png)
2.  i think for this one, we can just remove it.
![image](https://user-images.githubusercontent.com/46663012/116078641-0fdd6a80-a6c1-11eb-9ee7-bb28b96ee34c.png)

2021-04-26 12:21 UTC, rosudhi approved these changes
Perfect!

2021-04-28 09:52 UTC, merged