Front 9 add use local storage
DHI/react-components pull request #153
Opened 2021-07-05 14:34 UTC by brigittarucz

## Submission criteria

Please review the below criteria before asking for a review.

### Fulfilled the scope of this repo?

- [ ] The same functionality of the component can not be achieved with theming, basic styling or composition of existing components
- [ ] The component implements an element of the [DHI Design Guidelines](https://www.figma.com/file/pSfX5GNsa6xhKGbi3DWQtn/DHI-Official-Guidelines) or is otherwise generic enough in functionality and close enough to the DHI CVI that it is likely to find reuse in other projects

### Completness

- [ ] Story included

2021-07-05 14:55 UTC, bertearazvan requested changes
Nice job!! 💯 

In order for the hook to be exported from the library, you have to export it from here as well https://github.com/DHI/react-components/blob/FRONT-9-add-useLocalStorage/packages/react-components-lab/src/index.ts

2021-07-05 14:55 UTC, bertearazvan commented on packages/react-components-lab/src/hooks/useLocalStorage/types.ts
> +export { InitialVal, HookTypes };
```suggestion
export interface InitialVal {
  initialValue: unknown;
}

export interface HookTypes extends InitialVal {
  key: string;
}
```

You could do this instead, just a suggestion. I think that's how we do the export in other ones too.

2021-07-06 07:10 UTC, brigittarucz commented
@bertearazvan I have brought the necessary modifications - decided to exclude String as a function on setStorageValue. Semantic release will be working on master? :satellite:

2021-07-06 07:11 UTC, brigittarucz commented on packages/react-components-lab/src/hooks/useLocalStorage/types.ts
> +export { InitialVal, HookTypes };
Thank you! Done

2021-07-06 07:12 UTC, rihr approved these changes

2021-07-06 07:12 UTC, rihr commented on packages/react-components-lab/src/hooks/useLocalStorage/types.ts
> +interface InitialVal {
This isn't exported still. Is it actually used anywhere?

2021-07-06 07:17 UTC, bertearazvan commented
> @bertearazvan I have brought the necessary modifications - decided to exclude String as a function on setStorageValue. Semantic release will be working on master? 📡

Yes it should work once you merge

2021-07-06 07:29 UTC, bertearazvan approved these changes

2021-07-06 07:33 UTC, brigittarucz commented on packages/react-components-lab/src/hooks/useLocalStorage/types.ts
> +interface InitialVal {
It was not exported because only HookTypes was using it. I removed it completely and I combined the two now

2021-07-06 07:41 UTC, merged