feat(categoricalLegend): Add CategoricalLegend component
DHI/react-components pull request #205
Opened 2021-10-04 13:37 UTC by brigittarucz

## This PR

- [ ] Ticks this box and Closes #100000

## Submission criteria

Please review the below criteria before asking for a review.

### Fulfilled the scope of this repo?

- [ ] The same functionality of the component can not be achieved with theming, basic styling or composition of existing components
- [ ] The component implements an element of the [DHI Design Guidelines](https://www.figma.com/file/pSfX5GNsa6xhKGbi3DWQtn/DHI-Official-Guidelines) or is otherwise generic enough in functionality and close enough to the DHI CVI that it is likely to find reuse in other projects

### Completness

- [ ] Story included

2021-10-04 14:16 UTC, bertearazvan requested changes
It looks good :) Nice component addition. 

I think that the idea with the 50/50 is good. It would be nice to actually have an example with `color secondary - Water extent,
color primary - Permanent water
`. Try to use the colors from the theme, as in [here](https://github.com/DHI/react-components/blob/master/packages/react-components-lab/src/components/ResizeHandle/ResizeHandle.stories.tsx#L15-L16). By this we provide a real-case scenario example and more than one color. 

What do you think of the name, @rihr? Do you have a better name suggestion? Maybe `CategoricalBarLegend` sounds better, as it's like the BarLegend. At the same time that implies a `ContinuousBarLegend` so I am not sure.

2021-10-04 14:19 UTC, brigittarucz commented
@bertearazvan Could you explain a bit more regarding those primary and secondary examples? ☀️

2021-10-04 14:20 UTC, rihr commented
CategoricalBarLegend should be good, or something else just to differentiate it from the overlay legend

2021-10-05 07:20 UTC, bertearazvan approved these changes

2021-10-05 08:27 UTC, merged