Finz/domain service ops/automation page
DHI/react-components pull request #356
Opened 2023-06-28 09:07 UTC by Finz-Azmi

## This PR

Closes #xxx

## Notes

- No notes to add

### Fulfilled the scope of this repo?

- [ ] The same functionality of the component can not be achieved with theming, basic styling or composition of existing components
- [ ] The component implements an element of the [DHI Design Guidelines](https://www.figma.com/file/pSfX5GNsa6xhKGbi3DWQtn/DHI-Official-Guidelines) or is otherwise generic enough in functionality and close enough to the DHI CVI that it is likely to find reuse in other projects

### Completness

- [ ] Story included

2023-07-03 01:57 UTC, FranzThomsen1089 requested changes

2023-07-03 01:57 UTC, FranzThomsen1089 commented on packages/react-components/src/Automations/Automations.stories.tsx
> +          jobRefferingPage={'jobs'}
Referring?

2023-07-03 02:09 UTC, Finz-Azmi commented on packages/react-components/src/Automations/Automations.stories.tsx
> +          jobRefferingPage={'jobs'}
there is a feature where when the user clicks a value from the Job Id column, it will refer to the Jobs Page, because the name of the job page is set in the configuration, so I added it in props to make it dynamic

2023-07-03 02:54 UTC, Finz-Azmi commented on packages/react-components/package.json
> +  "version": "0.8.23",
package number already updated @FranzThomsen1089

2023-07-06 03:44 UTC, FranzThomsen1089 requested changes

2023-07-06 03:44 UTC, FranzThomsen1089 commented on packages/react-components/src/Automations/Automations.stories.tsx
> +          jobRefferingPage={'jobs'}
No .. spelling mistake :)

2023-07-06 03:59 UTC, merged