update style and data to persist on collapsing
DHI/react-components pull request #77
Opened 2021-02-22 04:09 UTC by JeanLoureiro

2021-02-22 04:19 UTC, JeanLoureiro commented
to pass the React Components dumb component rule, we have to update this component. At the moment it only fetches from timeseries fullnames.

2021-02-22 04:23 UTC, FranzThomsen1089 requested changes

2021-02-22 04:23 UTC, FranzThomsen1089 commented on src/DataServices/DataServices.ts
> +const fetchTimeseriesfullNames = (dataSources: DataSource[], token: string, group: any) => {
F

2021-02-22 04:23 UTC, FranzThomsen1089 commented on src/DataServices/types.ts
> +  group?: string;
Props here should really be described

2021-02-22 04:57 UTC, JeanLoureiro commented on src/DataServices/types.ts
> +  group?: string;
updated

2021-02-22 04:58 UTC, JeanLoureiro commented on src/DataServices/DataServices.ts
> +const fetchTimeseriesfullNames = (dataSources: DataSource[], token: string, group: any) => {
updated

2021-03-01 01:16 UTC, FranzThomsen1089 approved these changes

2021-03-01 01:18 UTC, goneale approved these changes

2021-03-01 01:18 UTC, merged